In [1]:
# import os
# import pandas as pd

# shapes = pd.read_parquet('./eval/density/german/trends.parquet')

In [6]:
import numpy as np

def one_hot_encode(matrix):
    # Determine the maximum value in the matrix
    num_categories = np.max(matrix) + 1
    
    # Initialize an empty list to hold the one-hot encoded rows
    one_hot_matrix = []
    
    # Iterate over each row in the matrix
    for row in matrix:
        # One-hot encode each element in the row
        one_hot_row = [np.eye(num_categories)[elem] for elem in row]
        # Combine the one-hot encoded vectors back into a single row
        one_hot_matrix.append(one_hot_row)
    
    # Convert the list of lists to a numpy array
    return np.array(one_hot_matrix)

# Example matrix
matrix = np.array([
    [0, 2, 1],
    [1, 0, 2],
    [2, 1, 0]
])

# Convert to one-hot encoded matrix
one_hot_matrix = one_hot_encode(matrix)

print("Original Matrix:\n", matrix)
print("\nOne-Hot Encoded Matrix:\n", one_hot_matrix)

# flatten each row
one_hot_matrix = one_hot_matrix.reshape(one_hot_matrix.shape[0], -1)
print("\nFlattened One-Hot Encoded Matrix:\n", one_hot_matrix)


Original Matrix:
 [[0 2 1]
 [1 0 2]
 [2 1 0]]

One-Hot Encoded Matrix:
 [[[1. 0. 0.]
  [0. 0. 1.]
  [0. 1. 0.]]

 [[0. 1. 0.]
  [1. 0. 0.]
  [0. 0. 1.]]

 [[0. 0. 1.]
  [0. 1. 0.]
  [1. 0. 0.]]]

Flattened One-Hot Encoded Matrix:
 [[1. 0. 0. 0. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 1. 0. 1. 0. 0.]]
