In [4]:
import numpy as np

In [8]:
def categorical_to_onehot(categorical, categories=[2, 3]):
    # create a list to store the one-hot encoded values
    onehot = []
    
    # iterate over the columns of the categorical matrix
    for i in range(categorical.shape[1]):
        # create a one-hot encoded matrix for the i-th column
        onehot_i = np.eye(categories[i])[categorical[:, i]]
        
        # append the one-hot encoded matrix to the list
        onehot.append(onehot_i)
    
    # concatenate the one-hot encoded matrices along the columns
    return np.concatenate(onehot, axis=1)

In [10]:
# test
categorical = np.array([[0, 1], [1, 2], [2, 0]])
categories = [3, 3]
print(categorical_to_onehot(categorical, categories))

[[1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1.]
 [0. 0. 1. 1. 0. 0.]]
